name: CI Front-end

on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    name: Build do projeto Front-end
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8
          cache: true

      - name: Instalar dependências
        working-directory: ./frontend/atendimento-app
        run: pnpm install --frozen-lockfile

      - name: Construir aplicação
        working-directory: ./frontend/atendimento-app
        run: pnpm run build

      - name: Salvar artefato de build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/atendimento-app/.next
